from nrf24 import *

CHANNEL = 99
DATA_RATE = RF24_DATA_RATE.RATE_1MBPS
PA_LEVEL = RF24_PA.HIGH
RETRY_DELAY = 0.01
CHUNK_SIZE = 50
PAYLOAD_SIZE = RF24_PAYLOAD.ACK
SPI_SPEED = 1e6
COMPRESSION_LEVEL = 6
